name: test-windows

on:
  push:
    branches:
      - master
      - dev*
  pull_request:
    branches:
      - master
      - dev*

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        haxe: [4.2.5]
      fail-fast: true
    runs-on: windows-latest

    steps:
      # Checkout & install haxe + node
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe }}

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.11
        with:
          source: app/assets/css/app.scss
          destination: app/assets/css/app.min.css

      - run: haxe -version

      - run: haxe setup.hxml
      - run: haxelib list
      - run: cd app && npm run compile
